approval:check:
  stage: check-approval
  image: nikstep/gitlab-approve-checker-env:1.1.7
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cd /opt/approval-check
    - bash check.sh
