scheduled-approval:check:
  stage: check-approval
  image: nikstep/gitlab-approve-checker-env:1.1.5
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $APPROVAL_CHECKER_SCHEDULED_JOB_NAME == "scheduled-approval"
      when: always
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
  script:
    - bash /opt/approval-check/scheduled-check.sh
