scheduled-approval:check:
  stage: check-approval
  image: nikstep/gitlab-approve-checker-env:latest
  rules:
    - if: $APPROVAL_CHECKER_SCHEDULED_JOB_NAME == "scheduled-approval"
  script:
    - bash scheduled-check.sh
