scheduled-approval:check:
  stage: check-approval
  image: nikstep/gitlab-approve-checker-env:1.1.3
  rules:
    - if: $SCHEDULED_JOB_NAME == "scheduled-approval"
  script:
    - bash /opt/approval-check/scheduled-check.sh
