approval:check:
  stage: check-approval
  image: nikstep/gitlab-approve-checker-env:1.1.4
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - bash /opt/approval-check/check.sh
